FROM debian:stretch

ENV LIBEVENT_VERSION 2.1.8

RUN apt-get update -y && apt-get upgrade -y

RUN apt-get install -y git-core build-essential wget

RUN set -x \
    &&  apt-get install -y \
     --no-install-recommends \
      make automake autoconf libssl-dev gdb valgrind \
    && apt-get autoclean -y \
    && wget \
    https://github.com/libevent/libevent/releases/download/release-$LIBEVENT_VERSION-stable/libevent-$LIBEVENT_VERSION-stable.tar.gz \
    && tar xzvf libevent-$LIBEVENT_VERSION-stable.tar.gz && cd libevent-$LIBEVENT_VERSION-stable \
    && ./configure && make -j4 && make install \
    && cd .. && rm -rf libevent-$LIBEVENT_VERSION-stable.tar.gz libevent-$LIBEVENT_VERSION-stable

WORKDIR /opt/esocks

ADD . /opt/esocks

COPY . /opt/esocks

RUN ./autogen.sh && ./configure  --enable-debug --with-libevent=/usr/local && make install

EXPOSE 1080 1080

CMD $COMMAND
